#include <iostream>
#include <project.h>
#include "config.h" // config.h is generated by cmake and may contain usefull information

int main(int argc, char * argv[]) {
  std::cout << project::function() << std::endl;
  return 0;
}

