#include <iostream>

#include "config.h" // config.h is generated by cmake and may contain usefull information

int main(int argc, char * argv[])
{
    std::cout << "Are you ready to rock ? Yeaaaaaah !" << std::endl;
    return 0;
}

